variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

stages:
  - translate
  - prepare
  - test
  - build
  - deploy

create-translations:
  except:
    - schedules
  stage: translate
  image: ubuntu:22.04
  script:
    - apt-get update && apt-get install -y python3 python3-pip
    - pip3 install requests openai==1.55.3
    - python3 var/translate.py
  only:
    - master@esaqa/psono/psono-client

download-translations:
  except:
    - schedules
  stage: prepare
  image: python:3
  script:
    - pip install requests
    - if [ "$CI_COMMIT_REF_NAME" = "develop" ]; then python3 var/upload_translations.py; fi
    - python3 var/download_translations.py
  artifacts:
    name: "translations_$CI_COMMIT_REF_NAME"
    expire_in: never
    paths:
      - src/common/data/translations/
  only:
    - branches@esaqa/psono/psono-client
    - /^v[0-9]*\.[0-9]*\.[0-9]*$/

test-unittests:
  except:
    - schedules
  stage: test
  image: ubuntu:22.04
  script:
    - sh ./var/prep-build.sh
    - npm run test
#    - DEBIAN_FRONTEND="noninteractive" apt-get install -y --no-install-recommends xvfb x11vnc fluxbox xterm chromium-browser
#    - curl -fsSL https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
#    - echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
#    - apt-get update
#    - apt-get install -y google-chrome-stable
#    - karma start ./unittests/karma-chromium-headless.conf.js


test-linter:
  except:
    - schedules
  stage: test
  image: ubuntu:22.04
  script:
    - sh ./var/prep-build.sh
    - node var/update_public_suffix_list.js
    - npm run buildfirefox
    - npm install -g addons-linter@6.1.0
    - cat ./build/firefox/manifest.json
    - addons-linter --help
    - addons-linter ./build/firefox

test-vulnerability-scan:
  except:
    - schedules
  stage: test
  image: ubuntu:22.04
  script:
    - apt-get update
    - apt-get install -y ca-certificates curl gnupg
    - mkdir -p /etc/apt/keyrings
    - curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
    - echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_22.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
    - apt-get update
    - apt-get install -y nodejs
    - node --version
    - npm --version
    - npm audit --audit-level high --json --only=prod
  allow_failure: true

build-docker-image:
  except:
    - schedules
  stage: build
  image: ubuntu:22.04
  services:
    - name: docker:25-dind
      alias: docker
      command: ["--tls=false"]
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  dependencies:
    - download-translations
  script:
    - apt-get update && apt-get install -y curl iptables libdevmapper1.02.1
    - sh ./var/prep-build.sh
    - npm run buildwebclient
    - curl -fSL "https://download.docker.com/linux/ubuntu/dists/jammy/pool/stable/amd64/containerd.io_1.6.28-1_amd64.deb" -o containerd.deb && echo "3fcc3e44e6d507c346ae05bbaef8f4bb04dfa8da9f04af658537f7e373c91340 containerd.deb" | sha256sum -c -
    - curl -fSL "https://download.docker.com/linux/ubuntu/dists/jammy/pool/stable/amd64/docker-buildx-plugin_0.12.1-1~ubuntu.22.04~jammy_amd64.deb" -o docker-buildx-plugin.deb && echo "3fb7cd11fd9bf7c31d81c1afa96c023519d9e6e17422192aa4d0aa2767ed0776 docker-buildx-plugin.deb" | sha256sum -c -
    - curl -fSL "https://download.docker.com/linux/ubuntu/dists/jammy/pool/stable/amd64/docker-ce-cli_25.0.3-1~ubuntu.22.04~jammy_amd64.deb" -o docker-ce-cli.deb && echo "624abe860a3d9dd190c278263b3ae115d54ce1135774a79f84026a6ec6ebafd1 docker-ce-cli.deb" | sha256sum -c -
    - curl -fSL "https://download.docker.com/linux/ubuntu/dists/jammy/pool/stable/amd64/docker-ce_25.0.3-1~ubuntu.22.04~jammy_amd64.deb" -o docker-ce.deb && echo "63c7703814558a829ab3cc37c8018c050c9dad56f99c261090500f6c87821fd1 docker-ce.deb" | sha256sum -c -
    - dpkg -i ./containerd.deb ./docker-ce.deb ./docker-ce-cli.deb ./docker-buildx-plugin.deb
    - docker info
    - echo $CI_JOB_TOKEN | docker login --username=gitlab-ci-token --password-stdin registry.gitlab.com
    - docker context create builder
    - docker buildx create builder --use
    - docker buildx build --platform linux/amd64,linux/arm64 -t $CONTAINER_TEST_IMAGE --push --pull .
#    - docker build -t $CONTAINER_TEST_IMAGE --pull .
#    - docker push $CONTAINER_TEST_IMAGE
  only:
    - branches@esaqa/psono/psono-client
    - /^v[0-9]*\.[0-9]*\.[0-9]*$/


build-sbom:
  except:
    - schedules
  stage: build
  image: ubuntu:22.04
  script:
    - apt-get update && apt-get install -y curl
    - sh ./var/prep-build.sh
    - npx @cyclonedx/cyclonedx-npm > sbom.json
  artifacts:
    name: "sbom_$CI_COMMIT_REF_NAME"
    paths:
      - sbom.json
  only:
    - branches@esaqa/psono/psono-client
    - /^v[0-9]*\.[0-9]*\.[0-9]*$/


build-firefox-extension:
  except:
    - schedules
  stage: build
  image: ubuntu:22.04
  dependencies:
    - download-translations
  script:
    - apt-get update && apt-get install -y curl
    - sh ./var/prep-build.sh
    - node var/update_public_suffix_list.js
    - npm run buildfirefox
    - sh ./var/package-firefox-extension.sh
    - cp dist/firefox/psono.firefox.PW.zip firefox-extension.zip
  artifacts:
    name: "firefox_$CI_COMMIT_REF_NAME"
    paths:
      - firefox-extension.zip
      - build/firefox/
  only:
    - branches@esaqa/psono/psono-client
    - /^v[0-9]*\.[0-9]*\.[0-9]*$/


build-chrome-extension:
  except:
    - schedules
  stage: build
  image: ubuntu:22.04
  dependencies:
    - download-translations
  script:
    - apt-get update && apt-get install -y curl
    - sh ./var/prep-build.sh
    - node var/update_public_suffix_list.js
    - npm run buildchrome
    - sh ./var/package-chrome-extension.sh
    - cp dist/chrome/psono.chrome.PW.zip chrome-extension.zip
  artifacts:
    name: "chrome_$CI_COMMIT_REF_NAME"
    paths:
      - chrome-extension.zip
      - build/chrome/
  only:
    - branches@esaqa/psono/psono-client
    - /^v[0-9]*\.[0-9]*\.[0-9]*$/

build-webclient:
  except:
    - schedules
  stage: build
  image: ubuntu:22.04
  dependencies:
    - download-translations
  script:
    - apt-get update && apt-get install -y curl
    - sh ./var/prep-build.sh
    - npm run buildwebclient
    - sh ./var/package-webclient.sh
    - cp dist/webclient/psono.webclient.PW.zip webclient.zip
  artifacts:
    name: "webclient_$CI_COMMIT_REF_NAME"
    paths:
      - webclient.zip
      - build/webclient/
  only:
    - branches@esaqa/psono/psono-client
    - /^v[0-9]*\.[0-9]*\.[0-9]*$/

deploy-docker:
  except:
    - schedules
  stage: deploy
  image: docker:25.0.3-git
  dependencies: []
  services:
    - name: docker:25-dind
      alias: docker
      command: ["--tls=false"]
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo $CI_JOB_TOKEN | docker login --username=gitlab-ci-token --password-stdin registry.gitlab.com
    - echo $docker_hub_credentials | docker login --username=psonogitlab --password-stdin
    - sh ./var/deploy-docker.sh
  environment:
    name: production
    url: https://psono.pw
  only:
    - /^v[0-9]*\.[0-9]*\.[0-9]*$/


deploy-github:
  except:
    - schedules
  stage: deploy
  image: docker:25.0.3-git
  dependencies: []
  services:
    - name: docker:25-dind
      alias: docker
      command: ["--tls=false"]
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  script:
    - sh ./var/deploy-github.sh
  environment:
    name: github
    url: https://github.com/psono/psono-client
  only:
    - /^v[0-9]*\.[0-9]*\.[0-9]*$/


deploy-chrome:
  except:
    - schedules
  stage: deploy
  image: ubuntu:22.04
  dependencies:
    - build-chrome-extension
  script:
    - sh ./var/prep-build.sh
    - sh ./var/deploy-chrome-extension.sh
  environment:
    name: chrome-webstore
    url: https://chrome.google.com/webstore/detail/psonopw/eljmjmgjkbmpmfljlmklcfineebidmlo
  only:
    - /^v[0-9]*\.[0-9]*\.[0-9]*$/


deploy-edge:
  except:
    - schedules
  stage: deploy
  image: python:3.11-buster
  dependencies:
    - build-chrome-extension
  script:
    - mv chrome-extension.zip edge-extension.zip
    - pip install requests
    - python3 var/deploy_edge_extension.py
  environment:
    name: edge-webstore
    url: https://chrome.google.com/webstore/detail/psonopw/eljmjmgjkbmpmfljlmklcfineebidmlo
  only:
    - /^v[0-9]*\.[0-9]*\.[0-9]*$/


deploy-firefox:
  except:
    - schedules
  stage: deploy
  image: ubuntu:22.04
  dependencies:
    - build-firefox-extension
  script:
    - apt-get update && apt-get install -y zip
    - zip -r ../source.zip ./ -x firefox-extension.zip -x ./firefox-extension.zip -x "build/*" -x "./build/*" -x "dist/*" -x "./dist/*"
    - mv ../source.zip ./
    - sh ./var/prep-build.sh
    - sh ./var/deploy-firefox-extension.sh
  environment:
    name: firefox-webstore
    url: https://addons.mozilla.org/firefox/addon/psono-pw-password-manager/
  only:
    - /^v[0-9]*\.[0-9]*\.[0-9]*$/

deploy-changelog:
  except:
    - schedules
  stage: deploy
  image: ubuntu:22.04
  dependencies: []
  script:
    - sh ./var/deploy_changelog.sh
  environment:
    name: static.psono.com
    url: https://static.psono.com/gitlab.com/psono/psono-client/changelog.json
  only:
    - /^v[0-9]*\.[0-9]*\.[0-9]*$/


deploy-nightlyartifacts:
  except:
    - schedules
  stage: deploy
  image: ubuntu:22.04
  dependencies:
    - build-sbom
    - build-firefox-extension
    - build-chrome-extension
    - build-webclient
  script:
    - sh ./var/deploy_nightlyartifacts.sh
  environment:
    name: static.psono.com
    url: https://get.psono.com/psono/psono-client/nightly/chrome-extension.zip
  only:
    - develop@esaqa/psono/psono-client


deploy-releaseartifacts:
  except:
    - schedules
  stage: deploy
  image: ubuntu:22.04
  dependencies:
    - build-sbom
    - build-firefox-extension
    - build-chrome-extension
    - build-webclient
  script:
    - sh ./var/deploy_releaseartifacts.sh
  environment:
    name: static.psono.com
    url: https://get.psono.com/psono/psono-client/latest/chrome-extension.zip
  only:
    - /^v[0-9]*\.[0-9]*\.[0-9]*$/
